### ISSUE TITLE
Stops with error during initial scanning of instances.

### ISSUE THREAD

**Issue by frese** [kaytu-io/kaytu#36]
**Describe the bug**

failures: - Evaluating usage data for i-001de016c6050985d failed due to [requestAbout] : invalid character 'e' looking for beginning of value

**To Reproduce**

1. Connected to my AWS account ..
2. Run "kaytu"
3. See error

**Expected behavior**

Cost savings report I presume :-)

**Notes**
Several runs, stops with same failure at the same instance. I've investigated the instance, it's one of our databases thats been running for about a year. Nothing to see 🤷

**Comment by Mahanmmi** [comment]
Sounds like the client is getting an unexpected response from the server.
That can happen for a variety of reasons. I have updated the error report to be clear in such cases. 
If you could run the latest version and post the cleared-up error message, it should help expedite the resolution of the issue.

**Comment by frese** [comment]
Awesome, unfortunately this is what I get

`failures: - Evaluating usage data for i-001de016c6050985d failed due to server returned status code 504, [requestAbout] : error code: 504`

**Comment by Mahanmmi** [comment]
Thanks!
That means server didn't respond in a timely manner to the right sizing request and the request timed out in the load-balancer.
The client doesn't fetch the rightsizing of instances sequentially, it does send the request for all of them in parallel so one of them failing is not preventing others, in fact if I have to guess fetching all of them at the same time is overpowering the server, making it slow to respond hence it timing out. I'll try some adjustments and get back to you on it.

**Comment by acx1729** [comment]
Hi @frese  We didn't forget about this; the fix is rolled out in preview.

**Comment by frese** [comment]
Thanks - just updated to 0.7.4 and seems to be working now, aka. it's not crashing 👍🏼
