### ISSUE TITLE
Screen Size is too small

### ISSUE THREAD

**Issue by opie4624** [kaytu-io/kaytu#44]
**Describe the bug**
Each time kaytu is started, this error: `Application cannot be rendered in this screen size, please increase height of your terminal`

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.4.1 (23E224)

**Additional context**

```
➜ echo $LINES
67

~
➜ echo $COLUMNS
206
```

**Comment by opie4624** [comment]
Further debugging:
```
➜ echo $LINES lines x $COLUMNS columns
146 lines x 495 columns
```

<img width="1624" alt="Screenshot 2024-05-01 at 15 08 31" src="https://github.com/kaytu-io/kaytu/assets/6883/f0138b48-aea0-482d-8b1c-e75de21cdad3">
🤣

**Comment by salehkhazaei** [comment]
Hi @opie4624 

Please run `kaytu version` and let me know which version you are running. if it's not 0.5.5 please update the cli and let me know if it's fixed or not.

**Comment by acx1729** [comment]
Hi @opie4624 I think this is fixed in the latest release :)
