### ISSUE TITLE
Add progress bar for plugin installation

### ISSUE THREAD

**Issue by salehkhazaei** [kaytu-io/kaytu#68]
Currently there's no way to understand the progress of plugin installation and with huge plugins or slow connection user feels that it's stuck. 
We need to add proper progress bar
examples on how to implement:

https://github.com/charmbracelet/bubbletea/tree/master/examples/progress-animated
https://github.com/charmbracelet/bubbletea/tree/master/examples/progress-download
https://github.com/charmbracelet/bubbletea/tree/master/examples/progress-static

**Comment by Mahanmmi** [comment]
Added in #72
